# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee6b64a47e5ccae60d5fc578714d50063b5b2b96e2f3263ac848de5488ce439a4b754eb5e694fe4c1e1ead2e39b1fef53a6dae2cb394f746975ec92c74eab105

test:
  secret_key_base: 0accfa1d222891e164e60d05f633954a4941e694b55cee4bc62ea92fe28f0b6dd3606f870f60e7ad25068e6d81ff70899eb37d8f747356c43410d82cd36ad0e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
